import { createDict } from '@ff-kits/base'

export const Timezones = createDict({
  EtcGmt_12: {
    value: 'Etc/GMT-12',
    label: 'GMT+12:00 Etc/GMT-12',
    offset: 'GMT+12:00',
    locale: 'Etc/GMT-12',
  },
  EtcGmt_11: {
    value: 'Etc/GMT-11',
    label: 'GMT+11:00 Etc/GMT-11',
    offset: 'GMT+11:00',
    locale: 'Etc/GMT-11',
  },
  PacificMidway: {
    value: 'Pacific/Midway',
    label: 'GMT-11:00 Pacific/Midway',
    offset: 'GMT-11:00',
    locale: 'Pacific/Midway',
  },
  PacificNiue: {
    value: 'Pacific/Niue',
    label: 'GMT-11:00 Pacific/Niue',
    offset: 'GMT-11:00',
    locale: 'Pacific/Niue',
  },
  PacificPagoPago: {
    value: 'Pacific/Pago_Pago',
    label: 'GMT-11:00 Pacific/Pago Pago',
    offset: 'GMT-11:00',
    locale: 'Pacific/Pago_Pago',
  },
  AmericaAdak: {
    value: 'America/Adak',
    label: 'GMT-10:00 America/Adak',
    offset: 'GMT-10:00',
    locale: 'America/Adak',
  },
  EtcGmt_10: {
    value: 'Etc/GMT-10',
    label: 'GMT+10:00 Etc/GMT-10',
    offset: 'GMT+10:00',
    locale: 'Etc/GMT-10',
  },
  Hst: {
    value: 'HST',
    label: 'GMT-10:00 HST',
    offset: 'GMT-10:00',
    locale: 'HST',
  },
  PacificHonolulu: {
    value: 'Pacific/Honolulu',
    label: 'GMT-10:00 Pacific/Honolulu',
    offset: 'GMT-10:00',
    locale: 'Pacific/Honolulu',
  },
  PacificRarotonga: {
    value: 'Pacific/Rarotonga',
    label: 'GMT-10:00 Pacific/Rarotonga',
    offset: 'GMT-10:00',
    locale: 'Pacific/Rarotonga',
  },
  PacificTahiti: {
    value: 'Pacific/Tahiti',
    label: 'GMT-10:00 Pacific/Tahiti',
    offset: 'GMT-10:00',
    locale: 'Pacific/Tahiti',
  },
  PacificMarquesas: {
    value: 'Pacific/Marquesas',
    label: 'GMT-09:30 Pacific/Marquesas',
    offset: 'GMT-09:30',
    locale: 'Pacific/Marquesas',
  },
  AmericaMetlakatla: {
    value: 'America/Metlakatla',
    label: 'GMT-09:00 America/Metlakatla',
    offset: 'GMT-09:00',
    locale: 'America/Metlakatla',
  },
  AmericaAnchorage: {
    value: 'America/Anchorage',
    label: 'GMT-09:00 America/Anchorage',
    offset: 'GMT-09:00',
    locale: 'America/Anchorage',
  },
  AmericaJuneau: {
    value: 'America/Juneau',
    label: 'GMT-09:00 America/Juneau',
    offset: 'GMT-09:00',
    locale: 'America/Juneau',
  },
  AmericaNome: {
    value: 'America/Nome',
    label: 'GMT-09:00 America/Nome',
    offset: 'GMT-09:00',
    locale: 'America/Nome',
  },
  AmericaSitka: {
    value: 'America/Sitka',
    label: 'GMT-09:00 America/Sitka',
    offset: 'GMT-09:00',
    locale: 'America/Sitka',
  },
  AmericaYakutat: {
    value: 'America/Yakutat',
    label: 'GMT-09:00 America/Yakutat',
    offset: 'GMT-09:00',
    locale: 'America/Yakutat',
  },
  EtcGmt_9: {
    value: 'Etc/GMT-9',
    label: 'GMT+09:00 Etc/GMT-9',
    offset: 'GMT+09:00',
    locale: 'Etc/GMT-9',
  },
  PacificGambier: {
    value: 'Pacific/Gambier',
    label: 'GMT-09:00 Pacific/Gambier',
    offset: 'GMT-09:00',
    locale: 'Pacific/Gambier',
  },
  AmericaLosAngeles: {
    value: 'America/Los_Angeles',
    label: 'GMT-08:00 America/Los Angeles',
    offset: 'GMT-08:00',
    locale: 'America/Los_Angeles',
  },
  AmericaTijuana: {
    value: 'America/Tijuana',
    label: 'GMT-08:00 America/Tijuana',
    offset: 'GMT-08:00',
    locale: 'America/Tijuana',
  },
  AmericaVancouver: {
    value: 'America/Vancouver',
    label: 'GMT-08:00 America/Vancouver',
    offset: 'GMT-08:00',
    locale: 'America/Vancouver',
  },
  EtcGmt_8: {
    value: 'Etc/GMT-8',
    label: 'GMT+08:00 Etc/GMT-8',
    offset: 'GMT+08:00',
    locale: 'Etc/GMT-8',
  },
  Pst8Pdt: {
    value: 'PST8PDT',
    label: 'GMT-08:00 PST8PDT',
    offset: 'GMT-08:00',
    locale: 'PST8PDT',
  },
  PacificPitcairn: {
    value: 'Pacific/Pitcairn',
    label: 'GMT-08:00 Pacific/Pitcairn',
    offset: 'GMT-08:00',
    locale: 'Pacific/Pitcairn',
  },
  AmericaBoise: {
    value: 'America/Boise',
    label: 'GMT-07:00 America/Boise',
    offset: 'GMT-07:00',
    locale: 'America/Boise',
  },
  AmericaCambridgeBay: {
    value: 'America/Cambridge_Bay',
    label: 'GMT-07:00 America/Cambridge Bay',
    offset: 'GMT-07:00',
    locale: 'America/Cambridge_Bay',
  },
  AmericaChihuahua: {
    value: 'America/Chihuahua',
    label: 'GMT-07:00 America/Chihuahua',
    offset: 'GMT-07:00',
    locale: 'America/Chihuahua',
  },
  AmericaCreston: {
    value: 'America/Creston',
    label: 'GMT-07:00 America/Creston',
    offset: 'GMT-07:00',
    locale: 'America/Creston',
  },
  AmericaDawson: {
    value: 'America/Dawson',
    label: 'GMT-07:00 America/Dawson',
    offset: 'GMT-07:00',
    locale: 'America/Dawson',
  },
  AmericaDawsonCreek: {
    value: 'America/Dawson_Creek',
    label: 'GMT-07:00 America/Dawson Creek',
    offset: 'GMT-07:00',
    locale: 'America/Dawson_Creek',
  },
  AmericaDenver: {
    value: 'America/Denver',
    label: 'GMT-07:00 America/Denver',
    offset: 'GMT-07:00',
    locale: 'America/Denver',
  },
  AmericaEdmonton: {
    value: 'America/Edmonton',
    label: 'GMT-07:00 America/Edmonton',
    offset: 'GMT-07:00',
    locale: 'America/Edmonton',
  },
  AmericaFortNelson: {
    value: 'America/Fort_Nelson',
    label: 'GMT-07:00 America/Fort Nelson',
    offset: 'GMT-07:00',
    locale: 'America/Fort_Nelson',
  },
  AmericaHermosillo: {
    value: 'America/Hermosillo',
    label: 'GMT-07:00 America/Hermosillo',
    offset: 'GMT-07:00',
    locale: 'America/Hermosillo',
  },
  AmericaInuvik: {
    value: 'America/Inuvik',
    label: 'GMT-07:00 America/Inuvik',
    offset: 'GMT-07:00',
    locale: 'America/Inuvik',
  },
  AmericaMazatlan: {
    value: 'America/Mazatlan',
    label: 'GMT-07:00 America/Mazatlan',
    offset: 'GMT-07:00',
    locale: 'America/Mazatlan',
  },
  AmericaOjinaga: {
    value: 'America/Ojinaga',
    label: 'GMT-07:00 America/Ojinaga',
    offset: 'GMT-07:00',
    locale: 'America/Ojinaga',
  },
  AmericaPhoenix: {
    value: 'America/Phoenix',
    label: 'GMT-07:00 America/Phoenix',
    offset: 'GMT-07:00',
    locale: 'America/Phoenix',
  },
  AmericaWhitehorse: {
    value: 'America/Whitehorse',
    label: 'GMT-07:00 America/Whitehorse',
    offset: 'GMT-07:00',
    locale: 'America/Whitehorse',
  },
  AmericaYellowknife: {
    value: 'America/Yellowknife',
    label: 'GMT-07:00 America/Yellowknife',
    offset: 'GMT-07:00',
    locale: 'America/Yellowknife',
  },
  EtcGmt_7: {
    value: 'Etc/GMT-7',
    label: 'GMT+07:00 Etc/GMT-7',
    offset: 'GMT+07:00',
    locale: 'Etc/GMT-7',
  },
  Mst: {
    value: 'MST',
    label: 'GMT-07:00 MST',
    offset: 'GMT-07:00',
    locale: 'MST',
  },
  Mst7Mdt: {
    value: 'MST7MDT',
    label: 'GMT-07:00 MST7MDT',
    offset: 'GMT-07:00',
    locale: 'MST7MDT',
  },
  AmericaBahiaBanderas: {
    value: 'America/Bahia_Banderas',
    label: 'GMT-06:00 America/Bahia Banderas',
    offset: 'GMT-06:00',
    locale: 'America/Bahia_Banderas',
  },
  AmericaBelize: {
    value: 'America/Belize',
    label: 'GMT-06:00 America/Belize',
    offset: 'GMT-06:00',
    locale: 'America/Belize',
  },
  AmericaChicago: {
    value: 'America/Chicago',
    label: 'GMT-06:00 America/Chicago',
    offset: 'GMT-06:00',
    locale: 'America/Chicago',
  },
  AmericaCostaRica: {
    value: 'America/Costa_Rica',
    label: 'GMT-06:00 America/Costa Rica',
    offset: 'GMT-06:00',
    locale: 'America/Costa_Rica',
  },
  AmericaElSalvador: {
    value: 'America/El_Salvador',
    label: 'GMT-06:00 America/El Salvador',
    offset: 'GMT-06:00',
    locale: 'America/El_Salvador',
  },
  AmericaGuatemala: {
    value: 'America/Guatemala',
    label: 'GMT-06:00 America/Guatemala',
    offset: 'GMT-06:00',
    locale: 'America/Guatemala',
  },
  AmericaIndianaKnox: {
    value: 'America/Indiana/Knox',
    label: 'GMT-06:00 America/Indiana/Knox',
    offset: 'GMT-06:00',
    locale: 'America/Indiana/Knox',
  },
  AmericaIndianaTellCity: {
    value: 'America/Indiana/Tell_City',
    label: 'GMT-06:00 America/Indiana/Tell City',
    offset: 'GMT-06:00',
    locale: 'America/Indiana/Tell_City',
  },
  AmericaManagua: {
    value: 'America/Managua',
    label: 'GMT-06:00 America/Managua',
    offset: 'GMT-06:00',
    locale: 'America/Managua',
  },
  AmericaMatamoros: {
    value: 'America/Matamoros',
    label: 'GMT-06:00 America/Matamoros',
    offset: 'GMT-06:00',
    locale: 'America/Matamoros',
  },
  AmericaMenominee: {
    value: 'America/Menominee',
    label: 'GMT-06:00 America/Menominee',
    offset: 'GMT-06:00',
    locale: 'America/Menominee',
  },
  AmericaMerida: {
    value: 'America/Merida',
    label: 'GMT-06:00 America/Merida',
    offset: 'GMT-06:00',
    locale: 'America/Merida',
  },
  AmericaMexicoCity: {
    value: 'America/Mexico_City',
    label: 'GMT-06:00 America/Mexico City',
    offset: 'GMT-06:00',
    locale: 'America/Mexico_City',
  },
  AmericaMonterrey: {
    value: 'America/Monterrey',
    label: 'GMT-06:00 America/Monterrey',
    offset: 'GMT-06:00',
    locale: 'America/Monterrey',
  },
  AmericaNorthDakotaBeulah: {
    value: 'America/North_Dakota/Beulah',
    label: 'GMT-06:00 America/North Dakota/Beulah',
    offset: 'GMT-06:00',
    locale: 'America/North_Dakota/Beulah',
  },
  AmericaNorthDakotaCenter: {
    value: 'America/North_Dakota/Center',
    label: 'GMT-06:00 America/North Dakota/Center',
    offset: 'GMT-06:00',
    locale: 'America/North_Dakota/Center',
  },
  AmericaNorthDakotaNewSalem: {
    value: 'America/North_Dakota/New_Salem',
    label: 'GMT-06:00 America/North Dakota/New_Salem',
    offset: 'GMT-06:00',
    locale: 'America/North_Dakota/New_Salem',
  },
  AmericaRainyRiver: {
    value: 'America/Rainy_River',
    label: 'GMT-06:00 America/Rainy River',
    offset: 'GMT-06:00',
    locale: 'America/Rainy_River',
  },
  AmericaRankinInlet: {
    value: 'America/Rankin_Inlet',
    label: 'GMT-06:00 America/Rankin Inlet',
    offset: 'GMT-06:00',
    locale: 'America/Rankin_Inlet',
  },
  AmericaRegina: {
    value: 'America/Regina',
    label: 'GMT-06:00 America/Regina',
    offset: 'GMT-06:00',
    locale: 'America/Regina',
  },
  AmericaResolute: {
    value: 'America/Resolute',
    label: 'GMT-06:00 America/Resolute',
    offset: 'GMT-06:00',
    locale: 'America/Resolute',
  },
  AmericaSwiftCurrent: {
    value: 'America/Swift_Current',
    label: 'GMT-06:00 America/Swift Current',
    offset: 'GMT-06:00',
    locale: 'America/Swift_Current',
  },
  AmericaTegucigalpa: {
    value: 'America/Tegucigalpa',
    label: 'GMT-06:00 America/Tegucigalpa',
    offset: 'GMT-06:00',
    locale: 'America/Tegucigalpa',
  },
  AmericaWinnipeg: {
    value: 'America/Winnipeg',
    label: 'GMT-06:00 America/Winnipeg',
    offset: 'GMT-06:00',
    locale: 'America/Winnipeg',
  },
  Cst6Cdt: {
    value: 'CST6CDT',
    label: 'GMT-06:00 CST6CDT',
    offset: 'GMT-06:00',
    locale: 'CST6CDT',
  },
  EtcGmt_6: {
    value: 'Etc/GMT-6',
    label: 'GMT+06:00 Etc/GMT-6',
    offset: 'GMT+06:00',
    locale: 'Etc/GMT-6',
  },
  PacificGalapagos: {
    value: 'Pacific/Galapagos',
    label: 'GMT-06:00 Pacific/Galapagos',
    offset: 'GMT-06:00',
    locale: 'Pacific/Galapagos',
  },
  AmericaAtikokan: {
    value: 'America/Atikokan',
    label: 'GMT-05:00 America/Atikokan',
    offset: 'GMT-05:00',
    locale: 'America/Atikokan',
  },
  AmericaBogota: {
    value: 'America/Bogota',
    label: 'GMT-05:00 America/Bogota',
    offset: 'GMT-05:00',
    locale: 'America/Bogota',
  },
  AmericaCancun: {
    value: 'America/Cancun',
    label: 'GMT-05:00 America/Cancun',
    offset: 'GMT-05:00',
    locale: 'America/Cancun',
  },
  AmericaCayman: {
    value: 'America/Cayman',
    label: 'GMT-05:00 America/Cayman',
    offset: 'GMT-05:00',
    locale: 'America/Cayman',
  },
  AmericaDetroit: {
    value: 'America/Detroit',
    label: 'GMT-05:00 America/Detroit',
    offset: 'GMT-05:00',
    locale: 'America/Detroit',
  },
  AmericaEirunepe: {
    value: 'America/Eirunepe',
    label: 'GMT-05:00 America/Eirunepe',
    offset: 'GMT-05:00',
    locale: 'America/Eirunepe',
  },
  AmericaGrandTurk: {
    value: 'America/Grand_Turk',
    label: 'GMT-05:00 America/Grand Turk',
    offset: 'GMT-05:00',
    locale: 'America/Grand_Turk',
  },
  AmericaGuayaquil: {
    value: 'America/Guayaquil',
    label: 'GMT-05:00 America/Guayaquil',
    offset: 'GMT-05:00',
    locale: 'America/Guayaquil',
  },
  AmericaHavana: {
    value: 'America/Havana',
    label: 'GMT-05:00 America/Havana',
    offset: 'GMT-05:00',
    locale: 'America/Havana',
  },
  AmericaIndianaIndianapolis: {
    value: 'America/Indiana/Indianapolis',
    label: 'GMT-05:00 America/Indiana/Indianapolis',
    offset: 'GMT-05:00',
    locale: 'America/Indiana/Indianapolis',
  },
  AmericaIndianaMarengo: {
    value: 'America/Indiana/Marengo',
    label: 'GMT-05:00 America/Indiana/Marengo',
    offset: 'GMT-05:00',
    locale: 'America/Indiana/Marengo',
  },
  AmericaIndianaPetersburg: {
    value: 'America/Indiana/Petersburg',
    label: 'GMT-05:00 America/Indiana/Petersburg',
    offset: 'GMT-05:00',
    locale: 'America/Indiana/Petersburg',
  },
  AmericaIndianaVevay: {
    value: 'America/Indiana/Vevay',
    label: 'GMT-05:00 America/Indiana/Vevay',
    offset: 'GMT-05:00',
    locale: 'America/Indiana/Vevay',
  },
  AmericaIndianaVincennes: {
    value: 'America/Indiana/Vincennes',
    label: 'GMT-05:00 America/Indiana/Vincennes',
    offset: 'GMT-05:00',
    locale: 'America/Indiana/Vincennes',
  },
  AmericaIndianaWinamac: {
    value: 'America/Indiana/Winamac',
    label: 'GMT-05:00 America/Indiana/Winamac',
    offset: 'GMT-05:00',
    locale: 'America/Indiana/Winamac',
  },
  AmericaIndianapolis: {
    value: 'America/Indianapolis',
    label: 'GMT-05:00 America/Indianapolis',
    offset: 'GMT-05:00',
    locale: 'America/Indianapolis',
  },
  AmericaIqaluit: {
    value: 'America/Iqaluit',
    label: 'GMT-05:00 America/Iqaluit',
    offset: 'GMT-05:00',
    locale: 'America/Iqaluit',
  },
  AmericaJamaica: {
    value: 'America/Jamaica',
    label: 'GMT-05:00 America/Jamaica',
    offset: 'GMT-05:00',
    locale: 'America/Jamaica',
  },
  AmericaKentuckyLouisville: {
    value: 'America/Kentucky/Louisville',
    label: 'GMT-05:00 America/Kentucky/Louisville',
    offset: 'GMT-05:00',
    locale: 'America/Kentucky/Louisville',
  },
  AmericaKentuckyMonticello: {
    value: 'America/Kentucky/Monticello',
    label: 'GMT-05:00 America/Kentucky/Monticello',
    offset: 'GMT-05:00',
    locale: 'America/Kentucky/Monticello',
  },
  AmericaLima: {
    value: 'America/Lima',
    label: 'GMT-05:00 America/Lima',
    offset: 'GMT-05:00',
    locale: 'America/Lima',
  },
  AmericaMontreal: {
    value: 'America/Montreal',
    label: 'GMT-05:00 America/Montreal',
    offset: 'GMT-05:00',
    locale: 'America/Montreal',
  },
  AmericaNassau: {
    value: 'America/Nassau',
    label: 'GMT-05:00 America/Nassau',
    offset: 'GMT-05:00',
    locale: 'America/Nassau',
  },
  AmericaNewYork: {
    value: 'America/New_York',
    label: 'GMT-05:00 America/New York',
    offset: 'GMT-05:00',
    locale: 'America/New_York',
  },
  AmericaNipigon: {
    value: 'America/Nipigon',
    label: 'GMT-05:00 America/Nipigon',
    offset: 'GMT-05:00',
    locale: 'America/Nipigon',
  },
  AmericaPanama: {
    value: 'America/Panama',
    label: 'GMT-05:00 America/Panama',
    offset: 'GMT-05:00',
    locale: 'America/Panama',
  },
  AmericaPangnirtung: {
    value: 'America/Pangnirtung',
    label: 'GMT-05:00 America/Pangnirtung',
    offset: 'GMT-05:00',
    locale: 'America/Pangnirtung',
  },
  AmericaPortAuPrince: {
    value: 'America/Port-au-Prince',
    label: 'GMT-05:00 America/Port-au-Prince',
    offset: 'GMT-05:00',
    locale: 'America/Port-au-Prince',
  },
  AmericaRioBranco: {
    value: 'America/Rio_Branco',
    label: 'GMT-05:00 America/Rio Branco',
    offset: 'GMT-05:00',
    locale: 'America/Rio_Branco',
  },
  AmericaThunderBay: {
    value: 'America/Thunder_Bay',
    label: 'GMT-05:00 America/Thunder Bay',
    offset: 'GMT-05:00',
    locale: 'America/Thunder_Bay',
  },
  AmericaToronto: {
    value: 'America/Toronto',
    label: 'GMT-05:00 America/Toronto',
    offset: 'GMT-05:00',
    locale: 'America/Toronto',
  },
  Est: {
    value: 'EST',
    label: 'GMT-05:00 EST',
    offset: 'GMT-05:00',
    locale: 'EST',
  },
  Est5Edt: {
    value: 'EST5EDT',
    label: 'GMT-05:00 EST5EDT',
    offset: 'GMT-05:00',
    locale: 'EST5EDT',
  },
  EtcGmt_5: {
    value: 'Etc/GMT-5',
    label: 'GMT+05:00 Etc/GMT-5',
    offset: 'GMT+05:00',
    locale: 'Etc/GMT-5',
  },
  PacificEaster: {
    value: 'Pacific/Easter',
    label: 'GMT-05:00 Pacific/Easter',
    offset: 'GMT-05:00',
    locale: 'Pacific/Easter',
  },
  AmericaAnguilla: {
    value: 'America/Anguilla',
    label: 'GMT-04:00 America/Anguilla',
    offset: 'GMT-04:00',
    locale: 'America/Anguilla',
  },
  AmericaAntigua: {
    value: 'America/Antigua',
    label: 'GMT-04:00 America/Antigua',
    offset: 'GMT-04:00',
    locale: 'America/Antigua',
  },
  AmericaAruba: {
    value: 'America/Aruba',
    label: 'GMT-04:00 America/Aruba',
    offset: 'GMT-04:00',
    locale: 'America/Aruba',
  },
  AmericaBarbados: {
    value: 'America/Barbados',
    label: 'GMT-04:00 America/Barbados',
    offset: 'GMT-04:00',
    locale: 'America/Barbados',
  },
  AmericaBlancSablon: {
    value: 'America/Blanc-Sablon',
    label: 'GMT-04:00 America/Blanc-Sablon',
    offset: 'GMT-04:00',
    locale: 'America/Blanc-Sablon',
  },
  AmericaBoaVista: {
    value: 'America/Boa_Vista',
    label: 'GMT-04:00 America/Boa Vista',
    offset: 'GMT-04:00',
    locale: 'America/Boa_Vista',
  },
  AmericaCampoGrande: {
    value: 'America/Campo_Grande',
    label: 'GMT-04:00 America/Campo Grande',
    offset: 'GMT-04:00',
    locale: 'America/Campo_Grande',
  },
  AmericaCaracas: {
    value: 'America/Caracas',
    label: 'GMT-04:00 America/Caracas',
    offset: 'GMT-04:00',
    locale: 'America/Caracas',
  },
  AmericaCuiaba: {
    value: 'America/Cuiaba',
    label: 'GMT-04:00 America/Cuiaba',
    offset: 'GMT-04:00',
    locale: 'America/Cuiaba',
  },
  AmericaCuracao: {
    value: 'America/Curacao',
    label: 'GMT-04:00 America/Curacao',
    offset: 'GMT-04:00',
    locale: 'America/Curacao',
  },
  AmericaDominica: {
    value: 'America/Dominica',
    label: 'GMT-04:00 America/Dominica',
    offset: 'GMT-04:00',
    locale: 'America/Dominica',
  },
  AmericaGlaceBay: {
    value: 'America/Glace_Bay',
    label: 'GMT-04:00 America/Glace Bay',
    offset: 'GMT-04:00',
    locale: 'America/Glace_Bay',
  },
  AmericaGooseBay: {
    value: 'America/Goose_Bay',
    label: 'GMT-04:00 America/Goose Bay',
    offset: 'GMT-04:00',
    locale: 'America/Goose_Bay',
  },
  AmericaGrenada: {
    value: 'America/Grenada',
    label: 'GMT-04:00 America/Grenada',
    offset: 'GMT-04:00',
    locale: 'America/Grenada',
  },
  AmericaGuadeloupe: {
    value: 'America/Guadeloupe',
    label: 'GMT-04:00 America/Guadeloupe',
    offset: 'GMT-04:00',
    locale: 'America/Guadeloupe',
  },
  AmericaGuyana: {
    value: 'America/Guyana',
    label: 'GMT-04:00 America/Guyana',
    offset: 'GMT-04:00',
    locale: 'America/Guyana',
  },
  AmericaHalifax: {
    value: 'America/Halifax',
    label: 'GMT-04:00 America/Halifax',
    offset: 'GMT-04:00',
    locale: 'America/Halifax',
  },
  AmericaKralendijk: {
    value: 'America/Kralendijk',
    label: 'GMT-04:00 America/Kralendijk',
    offset: 'GMT-04:00',
    locale: 'America/Kralendijk',
  },
  AmericaLaPaz: {
    value: 'America/La_Paz',
    label: 'GMT-04:00 America/La Paz',
    offset: 'GMT-04:00',
    locale: 'America/La_Paz',
  },
  AmericaLowerPrinces: {
    value: 'America/Lower_Princes',
    label: 'GMT-04:00 America/Lower Princes',
    offset: 'GMT-04:00',
    locale: 'America/Lower_Princes',
  },
  AmericaManaus: {
    value: 'America/Manaus',
    label: 'GMT-04:00 America/Manaus',
    offset: 'GMT-04:00',
    locale: 'America/Manaus',
  },
  AmericaMarigot: {
    value: 'America/Marigot',
    label: 'GMT-04:00 America/Marigot',
    offset: 'GMT-04:00',
    locale: 'America/Marigot',
  },
  AmericaMartinique: {
    value: 'America/Martinique',
    label: 'GMT-04:00 America/Martinique',
    offset: 'GMT-04:00',
    locale: 'America/Martinique',
  },
  AmericaMoncton: {
    value: 'America/Moncton',
    label: 'GMT-04:00 America/Moncton',
    offset: 'GMT-04:00',
    locale: 'America/Moncton',
  },
  AmericaMontserrat: {
    value: 'America/Montserrat',
    label: 'GMT-04:00 America/Montserrat',
    offset: 'GMT-04:00',
    locale: 'America/Montserrat',
  },
  AmericaPortOfSpain: {
    value: 'America/Port_of_Spain',
    label: 'GMT-04:00 America/Port of_Spain',
    offset: 'GMT-04:00',
    locale: 'America/Port_of_Spain',
  },
  AmericaPortoVelho: {
    value: 'America/Porto_Velho',
    label: 'GMT-04:00 America/Porto Velho',
    offset: 'GMT-04:00',
    locale: 'America/Porto_Velho',
  },
  AmericaPuertoRico: {
    value: 'America/Puerto_Rico',
    label: 'GMT-04:00 America/Puerto Rico',
    offset: 'GMT-04:00',
    locale: 'America/Puerto_Rico',
  },
  AmericaSantoDomingo: {
    value: 'America/Santo_Domingo',
    label: 'GMT-04:00 America/Santo Domingo',
    offset: 'GMT-04:00',
    locale: 'America/Santo_Domingo',
  },
  AmericaStBarthelemy: {
    value: 'America/St_Barthelemy',
    label: 'GMT-04:00 America/St Barthelemy',
    offset: 'GMT-04:00',
    locale: 'America/St_Barthelemy',
  },
  AmericaStKitts: {
    value: 'America/St_Kitts',
    label: 'GMT-04:00 America/St Kitts',
    offset: 'GMT-04:00',
    locale: 'America/St_Kitts',
  },
  AmericaStLucia: {
    value: 'America/St_Lucia',
    label: 'GMT-04:00 America/St Lucia',
    offset: 'GMT-04:00',
    locale: 'America/St_Lucia',
  },
  AmericaStThomas: {
    value: 'America/St_Thomas',
    label: 'GMT-04:00 America/St Thomas',
    offset: 'GMT-04:00',
    locale: 'America/St_Thomas',
  },
  AmericaStVincent: {
    value: 'America/St_Vincent',
    label: 'GMT-04:00 America/St Vincent',
    offset: 'GMT-04:00',
    locale: 'America/St_Vincent',
  },
  AmericaThule: {
    value: 'America/Thule',
    label: 'GMT-04:00 America/Thule',
    offset: 'GMT-04:00',
    locale: 'America/Thule',
  },
  AmericaTortola: {
    value: 'America/Tortola',
    label: 'GMT-04:00 America/Tortola',
    offset: 'GMT-04:00',
    locale: 'America/Tortola',
  },
  AtlanticBermuda: {
    value: 'Atlantic/Bermuda',
    label: 'GMT-04:00 Atlantic/Bermuda',
    offset: 'GMT-04:00',
    locale: 'Atlantic/Bermuda',
  },
  EtcGmt_4: {
    value: 'Etc/GMT-4',
    label: 'GMT+04:00 Etc/GMT-4',
    offset: 'GMT+04:00',
    locale: 'Etc/GMT-4',
  },
  AmericaStJohns: {
    value: 'America/St_Johns',
    label: 'GMT-03:30 America/St Johns',
    offset: 'GMT-03:30',
    locale: 'America/St_Johns',
  },
  AmericaAraguaina: {
    value: 'America/Araguaina',
    label: 'GMT-03:00 America/Araguaina',
    offset: 'GMT-03:00',
    locale: 'America/Araguaina',
  },
  AmericaArgentinaBuenosAires: {
    value: 'America/Argentina/Buenos_Aires',
    label: 'GMT-03:00 America/Argentina/Buenos Aires',
    offset: 'GMT-03:00',
    locale: 'America/Argentina/Buenos_Aires',
  },
  AmericaArgentinaCatamarca: {
    value: 'America/Argentina/Catamarca',
    label: 'GMT-03:00 America/Argentina/Catamarca',
    offset: 'GMT-03:00',
    locale: 'America/Argentina/Catamarca',
  },
  AmericaArgentinaCordoba: {
    value: 'America/Argentina/Cordoba',
    label: 'GMT-03:00 America/Argentina/Cordoba',
    offset: 'GMT-03:00',
    locale: 'America/Argentina/Cordoba',
  },
  AmericaArgentinaJujuy: {
    value: 'America/Argentina/Jujuy',
    label: 'GMT-03:00 America/Argentina/Jujuy',
    offset: 'GMT-03:00',
    locale: 'America/Argentina/Jujuy',
  },
  AmericaArgentinaLaRioja: {
    value: 'America/Argentina/La_Rioja',
    label: 'GMT-03:00 America/Argentina/La Rioja',
    offset: 'GMT-03:00',
    locale: 'America/Argentina/La_Rioja',
  },
  AmericaArgentinaMendoza: {
    value: 'America/Argentina/Mendoza',
    label: 'GMT-03:00 America/Argentina/Mendoza',
    offset: 'GMT-03:00',
    locale: 'America/Argentina/Mendoza',
  },
  AmericaArgentinaRioGallegos: {
    value: 'America/Argentina/Rio_Gallegos',
    label: 'GMT-03:00 America/Argentina/Rio Gallegos',
    offset: 'GMT-03:00',
    locale: 'America/Argentina/Rio_Gallegos',
  },
  AmericaArgentinaSalta: {
    value: 'America/Argentina/Salta',
    label: 'GMT-03:00 America/Argentina/Salta',
    offset: 'GMT-03:00',
    locale: 'America/Argentina/Salta',
  },
  AmericaArgentinaSanJuan: {
    value: 'America/Argentina/San_Juan',
    label: 'GMT-03:00 America/Argentina/San Juan',
    offset: 'GMT-03:00',
    locale: 'America/Argentina/San_Juan',
  },
  AmericaArgentinaSanLuis: {
    value: 'America/Argentina/San_Luis',
    label: 'GMT-03:00 America/Argentina/San Luis',
    offset: 'GMT-03:00',
    locale: 'America/Argentina/San_Luis',
  },
  AmericaArgentinaTucuman: {
    value: 'America/Argentina/Tucuman',
    label: 'GMT-03:00 America/Argentina/Tucuman',
    offset: 'GMT-03:00',
    locale: 'America/Argentina/Tucuman',
  },
  AmericaArgentinaUshuaia: {
    value: 'America/Argentina/Ushuaia',
    label: 'GMT-03:00 America/Argentina/Ushuaia',
    offset: 'GMT-03:00',
    locale: 'America/Argentina/Ushuaia',
  },
  AmericaAsuncion: {
    value: 'America/Asuncion',
    label: 'GMT-03:00 America/Asuncion',
    offset: 'GMT-03:00',
    locale: 'America/Asuncion',
  },
  AmericaBahia: {
    value: 'America/Bahia',
    label: 'GMT-03:00 America/Bahia',
    offset: 'GMT-03:00',
    locale: 'America/Bahia',
  },
  AmericaBelem: {
    value: 'America/Belem',
    label: 'GMT-03:00 America/Belem',
    offset: 'GMT-03:00',
    locale: 'America/Belem',
  },
  AmericaCayenne: {
    value: 'America/Cayenne',
    label: 'GMT-03:00 America/Cayenne',
    offset: 'GMT-03:00',
    locale: 'America/Cayenne',
  },
  AmericaFortaleza: {
    value: 'America/Fortaleza',
    label: 'GMT-03:00 America/Fortaleza',
    offset: 'GMT-03:00',
    locale: 'America/Fortaleza',
  },
  AmericaGodthab: {
    value: 'America/Godthab',
    label: 'GMT-03:00 America/Godthab',
    offset: 'GMT-03:00',
    locale: 'America/Godthab',
  },
  AmericaMaceio: {
    value: 'America/Maceio',
    label: 'GMT-03:00 America/Maceio',
    offset: 'GMT-03:00',
    locale: 'America/Maceio',
  },
  AmericaMiquelon: {
    value: 'America/Miquelon',
    label: 'GMT-03:00 America/Miquelon',
    offset: 'GMT-03:00',
    locale: 'America/Miquelon',
  },
  AmericaMontevideo: {
    value: 'America/Montevideo',
    label: 'GMT-03:00 America/Montevideo',
    offset: 'GMT-03:00',
    locale: 'America/Montevideo',
  },
  AmericaNuuk: {
    value: 'America/Nuuk',
    label: 'GMT-03:00 America/Nuuk',
    offset: 'GMT-03:00',
    locale: 'America/Nuuk',
  },
  AmericaParamaribo: {
    value: 'America/Paramaribo',
    label: 'GMT-03:00 America/Paramaribo',
    offset: 'GMT-03:00',
    locale: 'America/Paramaribo',
  },
  AmericaPuntaArenas: {
    value: 'America/Punta_Arenas',
    label: 'GMT-03:00 America/Punta Arenas',
    offset: 'GMT-03:00',
    locale: 'America/Punta_Arenas',
  },
  AmericaRecife: {
    value: 'America/Recife',
    label: 'GMT-03:00 America/Recife',
    offset: 'GMT-03:00',
    locale: 'America/Recife',
  },
  AmericaSantarem: {
    value: 'America/Santarem',
    label: 'GMT-03:00 America/Santarem',
    offset: 'GMT-03:00',
    locale: 'America/Santarem',
  },
  AmericaSantiago: {
    value: 'America/Santiago',
    label: 'GMT-03:00 America/Santiago',
    offset: 'GMT-03:00',
    locale: 'America/Santiago',
  },
  AmericaSaoPaulo: {
    value: 'America/Sao_Paulo',
    label: 'GMT-03:00 America/Sao Paulo',
    offset: 'GMT-03:00',
    locale: 'America/Sao_Paulo',
  },
  AntarcticaPalmer: {
    value: 'Antarctica/Palmer',
    label: 'GMT-03:00 Antarctica/Palmer',
    offset: 'GMT-03:00',
    locale: 'Antarctica/Palmer',
  },
  AntarcticaRothera: {
    value: 'Antarctica/Rothera',
    label: 'GMT-03:00 Antarctica/Rothera',
    offset: 'GMT-03:00',
    locale: 'Antarctica/Rothera',
  },
  AtlanticStanley: {
    value: 'Atlantic/Stanley',
    label: 'GMT-03:00 Atlantic/Stanley',
    offset: 'GMT-03:00',
    locale: 'Atlantic/Stanley',
  },
  EtcGmt_3: {
    value: 'Etc/GMT-3',
    label: 'GMT+03:00 Etc/GMT-3',
    offset: 'GMT+03:00',
    locale: 'Etc/GMT-3',
  },
  AmericaNoronha: {
    value: 'America/Noronha',
    label: 'GMT-02:00 America/Noronha',
    offset: 'GMT-02:00',
    locale: 'America/Noronha',
  },
  AtlanticSouthGeorgia: {
    value: 'Atlantic/South_Georgia',
    label: 'GMT-02:00 Atlantic/South Georgia',
    offset: 'GMT-02:00',
    locale: 'Atlantic/South_Georgia',
  },
  EtcGmt_2: {
    value: 'Etc/GMT-2',
    label: 'GMT+02:00 Etc/GMT-2',
    offset: 'GMT+02:00',
    locale: 'Etc/GMT-2',
  },
  AmericaScoresbysund: {
    value: 'America/Scoresbysund',
    label: 'GMT-01:00 America/Scoresbysund',
    offset: 'GMT-01:00',
    locale: 'America/Scoresbysund',
  },
  AtlanticAzores: {
    value: 'Atlantic/Azores',
    label: 'GMT-01:00 Atlantic/Azores',
    offset: 'GMT-01:00',
    locale: 'Atlantic/Azores',
  },
  AtlanticCapeVerde: {
    value: 'Atlantic/Cape_Verde',
    label: 'GMT-01:00 Atlantic/Cape Verde',
    offset: 'GMT-01:00',
    locale: 'Atlantic/Cape_Verde',
  },
  EtcGmt_1: {
    value: 'Etc/GMT-1',
    label: 'GMT+01:00 Etc/GMT-1',
    offset: 'GMT+01:00',
    locale: 'Etc/GMT-1',
  },
  AfricaAbidjan: {
    value: 'Africa/Abidjan',
    label: 'GMT+00:00 Africa/Abidjan',
    offset: 'GMT+00:00',
    locale: 'Africa/Abidjan',
  },
  AfricaAccra: {
    value: 'Africa/Accra',
    label: 'GMT+00:00 Africa/Accra',
    offset: 'GMT+00:00',
    locale: 'Africa/Accra',
  },
  AfricaBamako: {
    value: 'Africa/Bamako',
    label: 'GMT+00:00 Africa/Bamako',
    offset: 'GMT+00:00',
    locale: 'Africa/Bamako',
  },
  AfricaBanjul: {
    value: 'Africa/Banjul',
    label: 'GMT+00:00 Africa/Banjul',
    offset: 'GMT+00:00',
    locale: 'Africa/Banjul',
  },
  AfricaBissau: {
    value: 'Africa/Bissau',
    label: 'GMT+00:00 Africa/Bissau',
    offset: 'GMT+00:00',
    locale: 'Africa/Bissau',
  },
  AfricaConakry: {
    value: 'Africa/Conakry',
    label: 'GMT+00:00 Africa/Conakry',
    offset: 'GMT+00:00',
    locale: 'Africa/Conakry',
  },
  AfricaDakar: {
    value: 'Africa/Dakar',
    label: 'GMT+00:00 Africa/Dakar',
    offset: 'GMT+00:00',
    locale: 'Africa/Dakar',
  },
  AfricaFreetown: {
    value: 'Africa/Freetown',
    label: 'GMT+00:00 Africa/Freetown',
    offset: 'GMT+00:00',
    locale: 'Africa/Freetown',
  },
  AfricaLome: {
    value: 'Africa/Lome',
    label: 'GMT+00:00 Africa/Lome',
    offset: 'GMT+00:00',
    locale: 'Africa/Lome',
  },
  AfricaMonrovia: {
    value: 'Africa/Monrovia',
    label: 'GMT+00:00 Africa/Monrovia',
    offset: 'GMT+00:00',
    locale: 'Africa/Monrovia',
  },
  AfricaNouakchott: {
    value: 'Africa/Nouakchott',
    label: 'GMT+00:00 Africa/Nouakchott',
    offset: 'GMT+00:00',
    locale: 'Africa/Nouakchott',
  },
  AfricaOuagadougou: {
    value: 'Africa/Ouagadougou',
    label: 'GMT+00:00 Africa/Ouagadougou',
    offset: 'GMT+00:00',
    locale: 'Africa/Ouagadougou',
  },
  AfricaSaoTome: {
    value: 'Africa/Sao_Tome',
    label: 'GMT+00:00 Africa/Sao Tome',
    offset: 'GMT+00:00',
    locale: 'Africa/Sao_Tome',
  },
  AmericaDanmarkshavn: {
    value: 'America/Danmarkshavn',
    label: 'GMT+00:00 America/Danmarkshavn',
    offset: 'GMT+00:00',
    locale: 'America/Danmarkshavn',
  },
  AntarcticaTroll: {
    value: 'Antarctica/Troll',
    label: 'GMT+00:00 Antarctica/Troll',
    offset: 'GMT+00:00',
    locale: 'Antarctica/Troll',
  },
  AtlanticCanary: {
    value: 'Atlantic/Canary',
    label: 'GMT+00:00 Atlantic/Canary',
    offset: 'GMT+00:00',
    locale: 'Atlantic/Canary',
  },
  AtlanticFaroe: {
    value: 'Atlantic/Faroe',
    label: 'GMT+00:00 Atlantic/Faroe',
    offset: 'GMT+00:00',
    locale: 'Atlantic/Faroe',
  },
  AtlanticMadeira: {
    value: 'Atlantic/Madeira',
    label: 'GMT+00:00 Atlantic/Madeira',
    offset: 'GMT+00:00',
    locale: 'Atlantic/Madeira',
  },
  AtlanticReykjavik: {
    value: 'Atlantic/Reykjavik',
    label: 'GMT+00:00 Atlantic/Reykjavik',
    offset: 'GMT+00:00',
    locale: 'Atlantic/Reykjavik',
  },
  AtlanticStHelena: {
    value: 'Atlantic/St_Helena',
    label: 'GMT+00:00 Atlantic/St Helena',
    offset: 'GMT+00:00',
    locale: 'Atlantic/St_Helena',
  },
  EtcGmt: {
    value: 'Etc/GMT',
    label: 'GMT+00:00 Etc/GMT',
    offset: 'GMT+00:00',
    locale: 'Etc/GMT',
  },
  EtcGmt_0: {
    value: 'Etc/GMT-0',
    label: 'GMT+00:00 Etc/GMT-0',
    offset: 'GMT+00:00',
    locale: 'Etc/GMT-0',
  },
  EtcGmt0: {
    value: 'Etc/GMT0',
    label: 'GMT+00:00 Etc/GMT0',
    offset: 'GMT+00:00',
    locale: 'Etc/GMT0',
  },
  EtcGreenwich: {
    value: 'Etc/Greenwich',
    label: 'GMT+00:00 Etc/Greenwich',
    offset: 'GMT+00:00',
    locale: 'Etc/Greenwich',
  },
  EtcUniversal: {
    value: 'Etc/Universal',
    label: 'GMT+00:00 Etc/Universal',
    offset: 'GMT+00:00',
    locale: 'Etc/Universal',
  },
  EtcZulu: {
    value: 'Etc/Zulu',
    label: 'GMT+00:00 Etc/Zulu',
    offset: 'GMT+00:00',
    locale: 'Etc/Zulu',
  },
  EuropeDublin: {
    value: 'Europe/Dublin',
    label: 'GMT+00:00 Europe/Dublin',
    offset: 'GMT+00:00',
    locale: 'Europe/Dublin',
  },
  EuropeGuernsey: {
    value: 'Europe/Guernsey',
    label: 'GMT+00:00 Europe/Guernsey',
    offset: 'GMT+00:00',
    locale: 'Europe/Guernsey',
  },
  EuropeIsleOfMan: {
    value: 'Europe/Isle_of_Man',
    label: 'GMT+00:00 Europe/Isle of_Man',
    offset: 'GMT+00:00',
    locale: 'Europe/Isle_of_Man',
  },
  EuropeJersey: {
    value: 'Europe/Jersey',
    label: 'GMT+00:00 Europe/Jersey',
    offset: 'GMT+00:00',
    locale: 'Europe/Jersey',
  },
  EuropeLisbon: {
    value: 'Europe/Lisbon',
    label: 'GMT+00:00 Europe/Lisbon',
    offset: 'GMT+00:00',
    locale: 'Europe/Lisbon',
  },
  EuropeLondon: {
    value: 'Europe/London',
    label: 'GMT+00:00 Europe/London',
    offset: 'GMT+00:00',
    locale: 'Europe/London',
  },
  Gmt: {
    value: 'GMT',
    label: 'GMT+00:00 GMT',
    offset: 'GMT+00:00',
    locale: 'GMT',
  },
  Utc: {
    value: 'UTC',
    label: 'GMT+00:00 UTC',
    offset: 'GMT+00:00',
    locale: 'UTC',
  },
  Wet: {
    value: 'WET',
    label: 'GMT+00:00 WET',
    offset: 'GMT+00:00',
    locale: 'WET',
  },
  AfricaAlgiers: {
    value: 'Africa/Algiers',
    label: 'GMT+01:00 Africa/Algiers',
    offset: 'GMT+01:00',
    locale: 'Africa/Algiers',
  },
  AfricaBangui: {
    value: 'Africa/Bangui',
    label: 'GMT+01:00 Africa/Bangui',
    offset: 'GMT+01:00',
    locale: 'Africa/Bangui',
  },
  AfricaBrazzaville: {
    value: 'Africa/Brazzaville',
    label: 'GMT+01:00 Africa/Brazzaville',
    offset: 'GMT+01:00',
    locale: 'Africa/Brazzaville',
  },
  AfricaCasablanca: {
    value: 'Africa/Casablanca',
    label: 'GMT+01:00 Africa/Casablanca',
    offset: 'GMT+01:00',
    locale: 'Africa/Casablanca',
  },
  AfricaCeuta: {
    value: 'Africa/Ceuta',
    label: 'GMT+01:00 Africa/Ceuta',
    offset: 'GMT+01:00',
    locale: 'Africa/Ceuta',
  },
  AfricaDouala: {
    value: 'Africa/Douala',
    label: 'GMT+01:00 Africa/Douala',
    offset: 'GMT+01:00',
    locale: 'Africa/Douala',
  },
  AfricaElAaiun: {
    value: 'Africa/El_Aaiun',
    label: 'GMT+01:00 Africa/El Aaiun',
    offset: 'GMT+01:00',
    locale: 'Africa/El_Aaiun',
  },
  AfricaKinshasa: {
    value: 'Africa/Kinshasa',
    label: 'GMT+01:00 Africa/Kinshasa',
    offset: 'GMT+01:00',
    locale: 'Africa/Kinshasa',
  },
  AfricaLagos: {
    value: 'Africa/Lagos',
    label: 'GMT+01:00 Africa/Lagos',
    offset: 'GMT+01:00',
    locale: 'Africa/Lagos',
  },
  AfricaLibreville: {
    value: 'Africa/Libreville',
    label: 'GMT+01:00 Africa/Libreville',
    offset: 'GMT+01:00',
    locale: 'Africa/Libreville',
  },
  AfricaLuanda: {
    value: 'Africa/Luanda',
    label: 'GMT+01:00 Africa/Luanda',
    offset: 'GMT+01:00',
    locale: 'Africa/Luanda',
  },
  AfricaMalabo: {
    value: 'Africa/Malabo',
    label: 'GMT+01:00 Africa/Malabo',
    offset: 'GMT+01:00',
    locale: 'Africa/Malabo',
  },
  AfricaNdjamena: {
    value: 'Africa/Ndjamena',
    label: 'GMT+01:00 Africa/Ndjamena',
    offset: 'GMT+01:00',
    locale: 'Africa/Ndjamena',
  },
  AfricaNiamey: {
    value: 'Africa/Niamey',
    label: 'GMT+01:00 Africa/Niamey',
    offset: 'GMT+01:00',
    locale: 'Africa/Niamey',
  },
  AfricaPortoNovo: {
    value: 'Africa/Porto-Novo',
    label: 'GMT+01:00 Africa/Porto-Novo',
    offset: 'GMT+01:00',
    locale: 'Africa/Porto-Novo',
  },
  AfricaTunis: {
    value: 'Africa/Tunis',
    label: 'GMT+01:00 Africa/Tunis',
    offset: 'GMT+01:00',
    locale: 'Africa/Tunis',
  },
  ArcticLongyearbyen: {
    value: 'Arctic/Longyearbyen',
    label: 'GMT+01:00 Arctic/Longyearbyen',
    offset: 'GMT+01:00',
    locale: 'Arctic/Longyearbyen',
  },
  Cet: {
    value: 'CET',
    label: 'GMT+01:00 CET',
    offset: 'GMT+01:00',
    locale: 'CET',
  },
  EuropeAmsterdam: {
    value: 'Europe/Amsterdam',
    label: 'GMT+01:00 Europe/Amsterdam',
    offset: 'GMT+01:00',
    locale: 'Europe/Amsterdam',
  },
  EuropeAndorra: {
    value: 'Europe/Andorra',
    label: 'GMT+01:00 Europe/Andorra',
    offset: 'GMT+01:00',
    locale: 'Europe/Andorra',
  },
  EuropeBelgrade: {
    value: 'Europe/Belgrade',
    label: 'GMT+01:00 Europe/Belgrade',
    offset: 'GMT+01:00',
    locale: 'Europe/Belgrade',
  },
  EuropeBerlin: {
    value: 'Europe/Berlin',
    label: 'GMT+01:00 Europe/Berlin',
    offset: 'GMT+01:00',
    locale: 'Europe/Berlin',
  },
  EuropeBratislava: {
    value: 'Europe/Bratislava',
    label: 'GMT+01:00 Europe/Bratislava',
    offset: 'GMT+01:00',
    locale: 'Europe/Bratislava',
  },
  EuropeBrussels: {
    value: 'Europe/Brussels',
    label: 'GMT+01:00 Europe/Brussels',
    offset: 'GMT+01:00',
    locale: 'Europe/Brussels',
  },
  EuropeBudapest: {
    value: 'Europe/Budapest',
    label: 'GMT+01:00 Europe/Budapest',
    offset: 'GMT+01:00',
    locale: 'Europe/Budapest',
  },
  EuropeBusingen: {
    value: 'Europe/Busingen',
    label: 'GMT+01:00 Europe/Busingen',
    offset: 'GMT+01:00',
    locale: 'Europe/Busingen',
  },
  EuropeCopenhagen: {
    value: 'Europe/Copenhagen',
    label: 'GMT+01:00 Europe/Copenhagen',
    offset: 'GMT+01:00',
    locale: 'Europe/Copenhagen',
  },
  EuropeGibraltar: {
    value: 'Europe/Gibraltar',
    label: 'GMT+01:00 Europe/Gibraltar',
    offset: 'GMT+01:00',
    locale: 'Europe/Gibraltar',
  },
  EuropeLjubljana: {
    value: 'Europe/Ljubljana',
    label: 'GMT+01:00 Europe/Ljubljana',
    offset: 'GMT+01:00',
    locale: 'Europe/Ljubljana',
  },
  EuropeLuxembourg: {
    value: 'Europe/Luxembourg',
    label: 'GMT+01:00 Europe/Luxembourg',
    offset: 'GMT+01:00',
    locale: 'Europe/Luxembourg',
  },
  EuropeMadrid: {
    value: 'Europe/Madrid',
    label: 'GMT+01:00 Europe/Madrid',
    offset: 'GMT+01:00',
    locale: 'Europe/Madrid',
  },
  EuropeMalta: {
    value: 'Europe/Malta',
    label: 'GMT+01:00 Europe/Malta',
    offset: 'GMT+01:00',
    locale: 'Europe/Malta',
  },
  EuropeMonaco: {
    value: 'Europe/Monaco',
    label: 'GMT+01:00 Europe/Monaco',
    offset: 'GMT+01:00',
    locale: 'Europe/Monaco',
  },
  EuropeOslo: {
    value: 'Europe/Oslo',
    label: 'GMT+01:00 Europe/Oslo',
    offset: 'GMT+01:00',
    locale: 'Europe/Oslo',
  },
  EuropeParis: {
    value: 'Europe/Paris',
    label: 'GMT+01:00 Europe/Paris',
    offset: 'GMT+01:00',
    locale: 'Europe/Paris',
  },
  EuropePodgorica: {
    value: 'Europe/Podgorica',
    label: 'GMT+01:00 Europe/Podgorica',
    offset: 'GMT+01:00',
    locale: 'Europe/Podgorica',
  },
  EuropePrague: {
    value: 'Europe/Prague',
    label: 'GMT+01:00 Europe/Prague',
    offset: 'GMT+01:00',
    locale: 'Europe/Prague',
  },
  EuropeRome: {
    value: 'Europe/Rome',
    label: 'GMT+01:00 Europe/Rome',
    offset: 'GMT+01:00',
    locale: 'Europe/Rome',
  },
  EuropeSanMarino: {
    value: 'Europe/San_Marino',
    label: 'GMT+01:00 Europe/San Marino',
    offset: 'GMT+01:00',
    locale: 'Europe/San_Marino',
  },
  EuropeSarajevo: {
    value: 'Europe/Sarajevo',
    label: 'GMT+01:00 Europe/Sarajevo',
    offset: 'GMT+01:00',
    locale: 'Europe/Sarajevo',
  },
  EuropeSkopje: {
    value: 'Europe/Skopje',
    label: 'GMT+01:00 Europe/Skopje',
    offset: 'GMT+01:00',
    locale: 'Europe/Skopje',
  },
  EuropeStockholm: {
    value: 'Europe/Stockholm',
    label: 'GMT+01:00 Europe/Stockholm',
    offset: 'GMT+01:00',
    locale: 'Europe/Stockholm',
  },
  EuropeTirane: {
    value: 'Europe/Tirane',
    label: 'GMT+01:00 Europe/Tirane',
    offset: 'GMT+01:00',
    locale: 'Europe/Tirane',
  },
  EuropeVaduz: {
    value: 'Europe/Vaduz',
    label: 'GMT+01:00 Europe/Vaduz',
    offset: 'GMT+01:00',
    locale: 'Europe/Vaduz',
  },
  EuropeVatican: {
    value: 'Europe/Vatican',
    label: 'GMT+01:00 Europe/Vatican',
    offset: 'GMT+01:00',
    locale: 'Europe/Vatican',
  },
  EuropeVienna: {
    value: 'Europe/Vienna',
    label: 'GMT+01:00 Europe/Vienna',
    offset: 'GMT+01:00',
    locale: 'Europe/Vienna',
  },
  EuropeWarsaw: {
    value: 'Europe/Warsaw',
    label: 'GMT+01:00 Europe/Warsaw',
    offset: 'GMT+01:00',
    locale: 'Europe/Warsaw',
  },
  EuropeZagreb: {
    value: 'Europe/Zagreb',
    label: 'GMT+01:00 Europe/Zagreb',
    offset: 'GMT+01:00',
    locale: 'Europe/Zagreb',
  },
  EuropeZurich: {
    value: 'Europe/Zurich',
    label: 'GMT+01:00 Europe/Zurich',
    offset: 'GMT+01:00',
    locale: 'Europe/Zurich',
  },
  Met: {
    value: 'MET',
    label: 'GMT+01:00 MET',
    offset: 'GMT+01:00',
    locale: 'MET',
  },
  AfricaBlantyre: {
    value: 'Africa/Blantyre',
    label: 'GMT+02:00 Africa/Blantyre',
    offset: 'GMT+02:00',
    locale: 'Africa/Blantyre',
  },
  AfricaBujumbura: {
    value: 'Africa/Bujumbura',
    label: 'GMT+02:00 Africa/Bujumbura',
    offset: 'GMT+02:00',
    locale: 'Africa/Bujumbura',
  },
  AfricaCairo: {
    value: 'Africa/Cairo',
    label: 'GMT+02:00 Africa/Cairo',
    offset: 'GMT+02:00',
    locale: 'Africa/Cairo',
  },
  AfricaGaborone: {
    value: 'Africa/Gaborone',
    label: 'GMT+02:00 Africa/Gaborone',
    offset: 'GMT+02:00',
    locale: 'Africa/Gaborone',
  },
  AfricaHarare: {
    value: 'Africa/Harare',
    label: 'GMT+02:00 Africa/Harare',
    offset: 'GMT+02:00',
    locale: 'Africa/Harare',
  },
  AfricaJohannesburg: {
    value: 'Africa/Johannesburg',
    label: 'GMT+02:00 Africa/Johannesburg',
    offset: 'GMT+02:00',
    locale: 'Africa/Johannesburg',
  },
  AfricaKhartoum: {
    value: 'Africa/Khartoum',
    label: 'GMT+02:00 Africa/Khartoum',
    offset: 'GMT+02:00',
    locale: 'Africa/Khartoum',
  },
  AfricaKigali: {
    value: 'Africa/Kigali',
    label: 'GMT+02:00 Africa/Kigali',
    offset: 'GMT+02:00',
    locale: 'Africa/Kigali',
  },
  AfricaLubumbashi: {
    value: 'Africa/Lubumbashi',
    label: 'GMT+02:00 Africa/Lubumbashi',
    offset: 'GMT+02:00',
    locale: 'Africa/Lubumbashi',
  },
  AfricaLusaka: {
    value: 'Africa/Lusaka',
    label: 'GMT+02:00 Africa/Lusaka',
    offset: 'GMT+02:00',
    locale: 'Africa/Lusaka',
  },
  AfricaMaputo: {
    value: 'Africa/Maputo',
    label: 'GMT+02:00 Africa/Maputo',
    offset: 'GMT+02:00',
    locale: 'Africa/Maputo',
  },
  AfricaMaseru: {
    value: 'Africa/Maseru',
    label: 'GMT+02:00 Africa/Maseru',
    offset: 'GMT+02:00',
    locale: 'Africa/Maseru',
  },
  AfricaMbabane: {
    value: 'Africa/Mbabane',
    label: 'GMT+02:00 Africa/Mbabane',
    offset: 'GMT+02:00',
    locale: 'Africa/Mbabane',
  },
  AfricaTripoli: {
    value: 'Africa/Tripoli',
    label: 'GMT+02:00 Africa/Tripoli',
    offset: 'GMT+02:00',
    locale: 'Africa/Tripoli',
  },
  AfricaWindhoek: {
    value: 'Africa/Windhoek',
    label: 'GMT+02:00 Africa/Windhoek',
    offset: 'GMT+02:00',
    locale: 'Africa/Windhoek',
  },
  AsiaAmman: {
    value: 'Asia/Amman',
    label: 'GMT+02:00 Asia/Amman',
    offset: 'GMT+02:00',
    locale: 'Asia/Amman',
  },
  AsiaBeirut: {
    value: 'Asia/Beirut',
    label: 'GMT+02:00 Asia/Beirut',
    offset: 'GMT+02:00',
    locale: 'Asia/Beirut',
  },
  AsiaDamascus: {
    value: 'Asia/Damascus',
    label: 'GMT+02:00 Asia/Damascus',
    offset: 'GMT+02:00',
    locale: 'Asia/Damascus',
  },
  AsiaFamagusta: {
    value: 'Asia/Famagusta',
    label: 'GMT+02:00 Asia/Famagusta',
    offset: 'GMT+02:00',
    locale: 'Asia/Famagusta',
  },
  AsiaGaza: {
    value: 'Asia/Gaza',
    label: 'GMT+02:00 Asia/Gaza',
    offset: 'GMT+02:00',
    locale: 'Asia/Gaza',
  },
  AsiaHebron: {
    value: 'Asia/Hebron',
    label: 'GMT+02:00 Asia/Hebron',
    offset: 'GMT+02:00',
    locale: 'Asia/Hebron',
  },
  AsiaJerusalem: {
    value: 'Asia/Jerusalem',
    label: 'GMT+02:00 Asia/Jerusalem',
    offset: 'GMT+02:00',
    locale: 'Asia/Jerusalem',
  },
  AsiaNicosia: {
    value: 'Asia/Nicosia',
    label: 'GMT+02:00 Asia/Nicosia',
    offset: 'GMT+02:00',
    locale: 'Asia/Nicosia',
  },
  Eet: {
    value: 'EET',
    label: 'GMT+02:00 EET',
    offset: 'GMT+02:00',
    locale: 'EET',
  },
  EuropeAthens: {
    value: 'Europe/Athens',
    label: 'GMT+02:00 Europe/Athens',
    offset: 'GMT+02:00',
    locale: 'Europe/Athens',
  },
  EuropeBucharest: {
    value: 'Europe/Bucharest',
    label: 'GMT+02:00 Europe/Bucharest',
    offset: 'GMT+02:00',
    locale: 'Europe/Bucharest',
  },
  EuropeChisinau: {
    value: 'Europe/Chisinau',
    label: 'GMT+02:00 Europe/Chisinau',
    offset: 'GMT+02:00',
    locale: 'Europe/Chisinau',
  },
  EuropeHelsinki: {
    value: 'Europe/Helsinki',
    label: 'GMT+02:00 Europe/Helsinki',
    offset: 'GMT+02:00',
    locale: 'Europe/Helsinki',
  },
  EuropeKaliningrad: {
    value: 'Europe/Kaliningrad',
    label: 'GMT+02:00 Europe/Kaliningrad',
    offset: 'GMT+02:00',
    locale: 'Europe/Kaliningrad',
  },
  EuropeKiev: {
    value: 'Europe/Kiev',
    label: 'GMT+02:00 Europe/Kiev',
    offset: 'GMT+02:00',
    locale: 'Europe/Kiev',
  },
  EuropeMariehamn: {
    value: 'Europe/Mariehamn',
    label: 'GMT+02:00 Europe/Mariehamn',
    offset: 'GMT+02:00',
    locale: 'Europe/Mariehamn',
  },
  EuropeNicosia: {
    value: 'Europe/Nicosia',
    label: 'GMT+02:00 Europe/Nicosia',
    offset: 'GMT+02:00',
    locale: 'Europe/Nicosia',
  },
  EuropeRiga: {
    value: 'Europe/Riga',
    label: 'GMT+02:00 Europe/Riga',
    offset: 'GMT+02:00',
    locale: 'Europe/Riga',
  },
  EuropeSofia: {
    value: 'Europe/Sofia',
    label: 'GMT+02:00 Europe/Sofia',
    offset: 'GMT+02:00',
    locale: 'Europe/Sofia',
  },
  EuropeTallinn: {
    value: 'Europe/Tallinn',
    label: 'GMT+02:00 Europe/Tallinn',
    offset: 'GMT+02:00',
    locale: 'Europe/Tallinn',
  },
  EuropeUzhgorod: {
    value: 'Europe/Uzhgorod',
    label: 'GMT+02:00 Europe/Uzhgorod',
    offset: 'GMT+02:00',
    locale: 'Europe/Uzhgorod',
  },
  EuropeVilnius: {
    value: 'Europe/Vilnius',
    label: 'GMT+02:00 Europe/Vilnius',
    offset: 'GMT+02:00',
    locale: 'Europe/Vilnius',
  },
  EuropeZaporozhye: {
    value: 'Europe/Zaporozhye',
    label: 'GMT+02:00 Europe/Zaporozhye',
    offset: 'GMT+02:00',
    locale: 'Europe/Zaporozhye',
  },
  AfricaAddisAbaba: {
    value: 'Africa/Addis_Ababa',
    label: 'GMT+03:00 Africa/Addis Ababa',
    offset: 'GMT+03:00',
    locale: 'Africa/Addis_Ababa',
  },
  AfricaAsmara: {
    value: 'Africa/Asmara',
    label: 'GMT+03:00 Africa/Asmara',
    offset: 'GMT+03:00',
    locale: 'Africa/Asmara',
  },
  AfricaDarEsSalaam: {
    value: 'Africa/Dar_es_Salaam',
    label: 'GMT+03:00 Africa/Dar es_Salaam',
    offset: 'GMT+03:00',
    locale: 'Africa/Dar_es_Salaam',
  },
  AfricaDjibouti: {
    value: 'Africa/Djibouti',
    label: 'GMT+03:00 Africa/Djibouti',
    offset: 'GMT+03:00',
    locale: 'Africa/Djibouti',
  },
  AfricaJuba: {
    value: 'Africa/Juba',
    label: 'GMT+03:00 Africa/Juba',
    offset: 'GMT+03:00',
    locale: 'Africa/Juba',
  },
  AfricaKampala: {
    value: 'Africa/Kampala',
    label: 'GMT+03:00 Africa/Kampala',
    offset: 'GMT+03:00',
    locale: 'Africa/Kampala',
  },
  AfricaMogadishu: {
    value: 'Africa/Mogadishu',
    label: 'GMT+03:00 Africa/Mogadishu',
    offset: 'GMT+03:00',
    locale: 'Africa/Mogadishu',
  },
  AfricaNairobi: {
    value: 'Africa/Nairobi',
    label: 'GMT+03:00 Africa/Nairobi',
    offset: 'GMT+03:00',
    locale: 'Africa/Nairobi',
  },
  AntarcticaSyowa: {
    value: 'Antarctica/Syowa',
    label: 'GMT+03:00 Antarctica/Syowa',
    offset: 'GMT+03:00',
    locale: 'Antarctica/Syowa',
  },
  AsiaAden: {
    value: 'Asia/Aden',
    label: 'GMT+03:00 Asia/Aden',
    offset: 'GMT+03:00',
    locale: 'Asia/Aden',
  },
  AsiaBaghdad: {
    value: 'Asia/Baghdad',
    label: 'GMT+03:00 Asia/Baghdad',
    offset: 'GMT+03:00',
    locale: 'Asia/Baghdad',
  },
  AsiaBahrain: {
    value: 'Asia/Bahrain',
    label: 'GMT+03:00 Asia/Bahrain',
    offset: 'GMT+03:00',
    locale: 'Asia/Bahrain',
  },
  AsiaIstanbul: {
    value: 'Asia/Istanbul',
    label: 'GMT+03:00 Asia/Istanbul',
    offset: 'GMT+03:00',
    locale: 'Asia/Istanbul',
  },
  AsiaKuwait: {
    value: 'Asia/Kuwait',
    label: 'GMT+03:00 Asia/Kuwait',
    offset: 'GMT+03:00',
    locale: 'Asia/Kuwait',
  },
  AsiaQatar: {
    value: 'Asia/Qatar',
    label: 'GMT+03:00 Asia/Qatar',
    offset: 'GMT+03:00',
    locale: 'Asia/Qatar',
  },
  AsiaRiyadh: {
    value: 'Asia/Riyadh',
    label: 'GMT+03:00 Asia/Riyadh',
    offset: 'GMT+03:00',
    locale: 'Asia/Riyadh',
  },
  EuropeIstanbul: {
    value: 'Europe/Istanbul',
    label: 'GMT+03:00 Europe/Istanbul',
    offset: 'GMT+03:00',
    locale: 'Europe/Istanbul',
  },
  EuropeKirov: {
    value: 'Europe/Kirov',
    label: 'GMT+03:00 Europe/Kirov',
    offset: 'GMT+03:00',
    locale: 'Europe/Kirov',
  },
  EuropeMinsk: {
    value: 'Europe/Minsk',
    label: 'GMT+03:00 Europe/Minsk',
    offset: 'GMT+03:00',
    locale: 'Europe/Minsk',
  },
  EuropeMoscow: {
    value: 'Europe/Moscow',
    label: 'GMT+03:00 Europe/Moscow',
    offset: 'GMT+03:00',
    locale: 'Europe/Moscow',
  },
  EuropeSimferopol: {
    value: 'Europe/Simferopol',
    label: 'GMT+03:00 Europe/Simferopol',
    offset: 'GMT+03:00',
    locale: 'Europe/Simferopol',
  },
  IndianAntananarivo: {
    value: 'Indian/Antananarivo',
    label: 'GMT+03:00 Indian/Antananarivo',
    offset: 'GMT+03:00',
    locale: 'Indian/Antananarivo',
  },
  IndianComoro: {
    value: 'Indian/Comoro',
    label: 'GMT+03:00 Indian/Comoro',
    offset: 'GMT+03:00',
    locale: 'Indian/Comoro',
  },
  IndianMayotte: {
    value: 'Indian/Mayotte',
    label: 'GMT+03:00 Indian/Mayotte',
    offset: 'GMT+03:00',
    locale: 'Indian/Mayotte',
  },
  AsiaTehran: {
    value: 'Asia/Tehran',
    label: 'GMT+03:30 Asia/Tehran',
    offset: 'GMT+03:30',
    locale: 'Asia/Tehran',
  },
  AsiaBaku: {
    value: 'Asia/Baku',
    label: 'GMT+04:00 Asia/Baku',
    offset: 'GMT+04:00',
    locale: 'Asia/Baku',
  },
  AsiaDubai: {
    value: 'Asia/Dubai',
    label: 'GMT+04:00 Asia/Dubai',
    offset: 'GMT+04:00',
    locale: 'Asia/Dubai',
  },
  AsiaMuscat: {
    value: 'Asia/Muscat',
    label: 'GMT+04:00 Asia/Muscat',
    offset: 'GMT+04:00',
    locale: 'Asia/Muscat',
  },
  AsiaTbilisi: {
    value: 'Asia/Tbilisi',
    label: 'GMT+04:00 Asia/Tbilisi',
    offset: 'GMT+04:00',
    locale: 'Asia/Tbilisi',
  },
  AsiaYerevan: {
    value: 'Asia/Yerevan',
    label: 'GMT+04:00 Asia/Yerevan',
    offset: 'GMT+04:00',
    locale: 'Asia/Yerevan',
  },
  EuropeAstrakhan: {
    value: 'Europe/Astrakhan',
    label: 'GMT+04:00 Europe/Astrakhan',
    offset: 'GMT+04:00',
    locale: 'Europe/Astrakhan',
  },
  EuropeSamara: {
    value: 'Europe/Samara',
    label: 'GMT+04:00 Europe/Samara',
    offset: 'GMT+04:00',
    locale: 'Europe/Samara',
  },
  EuropeSaratov: {
    value: 'Europe/Saratov',
    label: 'GMT+04:00 Europe/Saratov',
    offset: 'GMT+04:00',
    locale: 'Europe/Saratov',
  },
  EuropeUlyanovsk: {
    value: 'Europe/Ulyanovsk',
    label: 'GMT+04:00 Europe/Ulyanovsk',
    offset: 'GMT+04:00',
    locale: 'Europe/Ulyanovsk',
  },
  EuropeVolgograd: {
    value: 'Europe/Volgograd',
    label: 'GMT+04:00 Europe/Volgograd',
    offset: 'GMT+04:00',
    locale: 'Europe/Volgograd',
  },
  IndianMahe: {
    value: 'Indian/Mahe',
    label: 'GMT+04:00 Indian/Mahe',
    offset: 'GMT+04:00',
    locale: 'Indian/Mahe',
  },
  IndianMauritius: {
    value: 'Indian/Mauritius',
    label: 'GMT+04:00 Indian/Mauritius',
    offset: 'GMT+04:00',
    locale: 'Indian/Mauritius',
  },
  IndianReunion: {
    value: 'Indian/Reunion',
    label: 'GMT+04:00 Indian/Reunion',
    offset: 'GMT+04:00',
    locale: 'Indian/Reunion',
  },
  AsiaKabul: {
    value: 'Asia/Kabul',
    label: 'GMT+04:30 Asia/Kabul',
    offset: 'GMT+04:30',
    locale: 'Asia/Kabul',
  },
  AntarcticaMawson: {
    value: 'Antarctica/Mawson',
    label: 'GMT+05:00 Antarctica/Mawson',
    offset: 'GMT+05:00',
    locale: 'Antarctica/Mawson',
  },
  AsiaAqtau: {
    value: 'Asia/Aqtau',
    label: 'GMT+05:00 Asia/Aqtau',
    offset: 'GMT+05:00',
    locale: 'Asia/Aqtau',
  },
  AsiaAqtobe: {
    value: 'Asia/Aqtobe',
    label: 'GMT+05:00 Asia/Aqtobe',
    offset: 'GMT+05:00',
    locale: 'Asia/Aqtobe',
  },
  AsiaAshgabat: {
    value: 'Asia/Ashgabat',
    label: 'GMT+05:00 Asia/Ashgabat',
    offset: 'GMT+05:00',
    locale: 'Asia/Ashgabat',
  },
  AsiaAtyrau: {
    value: 'Asia/Atyrau',
    label: 'GMT+05:00 Asia/Atyrau',
    offset: 'GMT+05:00',
    locale: 'Asia/Atyrau',
  },
  AsiaDushanbe: {
    value: 'Asia/Dushanbe',
    label: 'GMT+05:00 Asia/Dushanbe',
    offset: 'GMT+05:00',
    locale: 'Asia/Dushanbe',
  },
  AsiaKarachi: {
    value: 'Asia/Karachi',
    label: 'GMT+05:00 Asia/Karachi',
    offset: 'GMT+05:00',
    locale: 'Asia/Karachi',
  },
  AsiaOral: {
    value: 'Asia/Oral',
    label: 'GMT+05:00 Asia/Oral',
    offset: 'GMT+05:00',
    locale: 'Asia/Oral',
  },
  AsiaQyzylorda: {
    value: 'Asia/Qyzylorda',
    label: 'GMT+05:00 Asia/Qyzylorda',
    offset: 'GMT+05:00',
    locale: 'Asia/Qyzylorda',
  },
  AsiaSamarkand: {
    value: 'Asia/Samarkand',
    label: 'GMT+05:00 Asia/Samarkand',
    offset: 'GMT+05:00',
    locale: 'Asia/Samarkand',
  },
  AsiaTashkent: {
    value: 'Asia/Tashkent',
    label: 'GMT+05:00 Asia/Tashkent',
    offset: 'GMT+05:00',
    locale: 'Asia/Tashkent',
  },
  AsiaYekaterinburg: {
    value: 'Asia/Yekaterinburg',
    label: 'GMT+05:00 Asia/Yekaterinburg',
    offset: 'GMT+05:00',
    locale: 'Asia/Yekaterinburg',
  },
  IndianKerguelen: {
    value: 'Indian/Kerguelen',
    label: 'GMT+05:00 Indian/Kerguelen',
    offset: 'GMT+05:00',
    locale: 'Indian/Kerguelen',
  },
  IndianMaldives: {
    value: 'Indian/Maldives',
    label: 'GMT+05:00 Indian/Maldives',
    offset: 'GMT+05:00',
    locale: 'Indian/Maldives',
  },
  AsiaCalcutta: {
    value: 'Asia/Calcutta',
    label: 'GMT+05:30 Asia/Calcutta',
    offset: 'GMT+05:30',
    locale: 'Asia/Calcutta',
  },
  AsiaColombo: {
    value: 'Asia/Colombo',
    label: 'GMT+05:30 Asia/Colombo',
    offset: 'GMT+05:30',
    locale: 'Asia/Colombo',
  },
  AsiaKolkata: {
    value: 'Asia/Kolkata',
    label: 'GMT+05:30 Asia/Kolkata',
    offset: 'GMT+05:30',
    locale: 'Asia/Kolkata',
  },
  AsiaKathmandu: {
    value: 'Asia/Kathmandu',
    label: 'GMT+05:45 Asia/Kathmandu',
    offset: 'GMT+05:45',
    locale: 'Asia/Kathmandu',
  },
  AsiaKatmandu: {
    value: 'Asia/Katmandu',
    label: 'GMT+05:45 Asia/Katmandu',
    offset: 'GMT+05:45',
    locale: 'Asia/Katmandu',
  },
  AntarcticaVostok: {
    value: 'Antarctica/Vostok',
    label: 'GMT+06:00 Antarctica/Vostok',
    offset: 'GMT+06:00',
    locale: 'Antarctica/Vostok',
  },
  AsiaAlmaty: {
    value: 'Asia/Almaty',
    label: 'GMT+06:00 Asia/Almaty',
    offset: 'GMT+06:00',
    locale: 'Asia/Almaty',
  },
  AsiaBishkek: {
    value: 'Asia/Bishkek',
    label: 'GMT+06:00 Asia/Bishkek',
    offset: 'GMT+06:00',
    locale: 'Asia/Bishkek',
  },
  AsiaDhaka: {
    value: 'Asia/Dhaka',
    label: 'GMT+06:00 Asia/Dhaka',
    offset: 'GMT+06:00',
    locale: 'Asia/Dhaka',
  },
  AsiaOmsk: {
    value: 'Asia/Omsk',
    label: 'GMT+06:00 Asia/Omsk',
    offset: 'GMT+06:00',
    locale: 'Asia/Omsk',
  },
  AsiaQostanay: {
    value: 'Asia/Qostanay',
    label: 'GMT+06:00 Asia/Qostanay',
    offset: 'GMT+06:00',
    locale: 'Asia/Qostanay',
  },
  AsiaThimphu: {
    value: 'Asia/Thimphu',
    label: 'GMT+06:00 Asia/Thimphu',
    offset: 'GMT+06:00',
    locale: 'Asia/Thimphu',
  },
  AsiaUrumqi: {
    value: 'Asia/Urumqi',
    label: 'GMT+06:00 Asia/Urumqi',
    offset: 'GMT+06:00',
    locale: 'Asia/Urumqi',
  },
  IndianChagos: {
    value: 'Indian/Chagos',
    label: 'GMT+06:00 Indian/Chagos',
    offset: 'GMT+06:00',
    locale: 'Indian/Chagos',
  },
  AsiaYangon: {
    value: 'Asia/Yangon',
    label: 'GMT+06:30 Asia/Yangon',
    offset: 'GMT+06:30',
    locale: 'Asia/Yangon',
  },
  IndianCocos: {
    value: 'Indian/Cocos',
    label: 'GMT+06:30 Indian/Cocos',
    offset: 'GMT+06:30',
    locale: 'Indian/Cocos',
  },
  AntarcticaDavis: {
    value: 'Antarctica/Davis',
    label: 'GMT+07:00 Antarctica/Davis',
    offset: 'GMT+07:00',
    locale: 'Antarctica/Davis',
  },
  AsiaBangkok: {
    value: 'Asia/Bangkok',
    label: 'GMT+07:00 Asia/Bangkok',
    offset: 'GMT+07:00',
    locale: 'Asia/Bangkok',
  },
  AsiaBarnaul: {
    value: 'Asia/Barnaul',
    label: 'GMT+07:00 Asia/Barnaul',
    offset: 'GMT+07:00',
    locale: 'Asia/Barnaul',
  },
  AsiaHoChiMinh: {
    value: 'Asia/Ho_Chi_Minh',
    label: 'GMT+07:00 Asia/Ho Chi_Minh',
    offset: 'GMT+07:00',
    locale: 'Asia/Ho_Chi_Minh',
  },
  AsiaHovd: {
    value: 'Asia/Hovd',
    label: 'GMT+07:00 Asia/Hovd',
    offset: 'GMT+07:00',
    locale: 'Asia/Hovd',
  },
  AsiaJakarta: {
    value: 'Asia/Jakarta',
    label: 'GMT+07:00 Asia/Jakarta',
    offset: 'GMT+07:00',
    locale: 'Asia/Jakarta',
  },
  AsiaKrasnoyarsk: {
    value: 'Asia/Krasnoyarsk',
    label: 'GMT+07:00 Asia/Krasnoyarsk',
    offset: 'GMT+07:00',
    locale: 'Asia/Krasnoyarsk',
  },
  AsiaNovokuznetsk: {
    value: 'Asia/Novokuznetsk',
    label: 'GMT+07:00 Asia/Novokuznetsk',
    offset: 'GMT+07:00',
    locale: 'Asia/Novokuznetsk',
  },
  AsiaNovosibirsk: {
    value: 'Asia/Novosibirsk',
    label: 'GMT+07:00 Asia/Novosibirsk',
    offset: 'GMT+07:00',
    locale: 'Asia/Novosibirsk',
  },
  AsiaPhnomPenh: {
    value: 'Asia/Phnom_Penh',
    label: 'GMT+07:00 Asia/Phnom Penh',
    offset: 'GMT+07:00',
    locale: 'Asia/Phnom_Penh',
  },
  AsiaPontianak: {
    value: 'Asia/Pontianak',
    label: 'GMT+07:00 Asia/Pontianak',
    offset: 'GMT+07:00',
    locale: 'Asia/Pontianak',
  },
  AsiaTomsk: {
    value: 'Asia/Tomsk',
    label: 'GMT+07:00 Asia/Tomsk',
    offset: 'GMT+07:00',
    locale: 'Asia/Tomsk',
  },
  AsiaVientiane: {
    value: 'Asia/Vientiane',
    label: 'GMT+07:00 Asia/Vientiane',
    offset: 'GMT+07:00',
    locale: 'Asia/Vientiane',
  },
  IndianChristmas: {
    value: 'Indian/Christmas',
    label: 'GMT+07:00 Indian/Christmas',
    offset: 'GMT+07:00',
    locale: 'Indian/Christmas',
  },
  AsiaBrunei: {
    value: 'Asia/Brunei',
    label: 'GMT+08:00 Asia/Brunei',
    offset: 'GMT+08:00',
    locale: 'Asia/Brunei',
  },
  AsiaChoibalsan: {
    value: 'Asia/Choibalsan',
    label: 'GMT+08:00 Asia/Choibalsan',
    offset: 'GMT+08:00',
    locale: 'Asia/Choibalsan',
  },
  AsiaHongKong: {
    value: 'Asia/Hong_Kong',
    label: 'GMT+08:00 Asia/Hong Kong',
    offset: 'GMT+08:00',
    locale: 'Asia/Hong_Kong',
  },
  AsiaIrkutsk: {
    value: 'Asia/Irkutsk',
    label: 'GMT+08:00 Asia/Irkutsk',
    offset: 'GMT+08:00',
    locale: 'Asia/Irkutsk',
  },
  AsiaKualaLumpur: {
    value: 'Asia/Kuala_Lumpur',
    label: 'GMT+08:00 Asia/Kuala Lumpur',
    offset: 'GMT+08:00',
    locale: 'Asia/Kuala_Lumpur',
  },
  AsiaKuching: {
    value: 'Asia/Kuching',
    label: 'GMT+08:00 Asia/Kuching',
    offset: 'GMT+08:00',
    locale: 'Asia/Kuching',
  },
  AsiaMacau: {
    value: 'Asia/Macau',
    label: 'GMT+08:00 Asia/Macau',
    offset: 'GMT+08:00',
    locale: 'Asia/Macau',
  },
  AsiaMakassar: {
    value: 'Asia/Makassar',
    label: 'GMT+08:00 Asia/Makassar',
    offset: 'GMT+08:00',
    locale: 'Asia/Makassar',
  },
  AsiaManila: {
    value: 'Asia/Manila',
    label: 'GMT+08:00 Asia/Manila',
    offset: 'GMT+08:00',
    locale: 'Asia/Manila',
  },
  AsiaShanghai: {
    value: 'Asia/Shanghai',
    label: 'GMT+08:00 Asia/Shanghai',
    offset: 'GMT+08:00',
    locale: 'Asia/Shanghai',
  },
  AsiaSingapore: {
    value: 'Asia/Singapore',
    label: 'GMT+08:00 Asia/Singapore',
    offset: 'GMT+08:00',
    locale: 'Asia/Singapore',
  },
  AsiaTaipei: {
    value: 'Asia/Taipei',
    label: 'GMT+08:00 Asia/Taipei',
    offset: 'GMT+08:00',
    locale: 'Asia/Taipei',
  },
  AsiaUlaanbaatar: {
    value: 'Asia/Ulaanbaatar',
    label: 'GMT+08:00 Asia/Ulaanbaatar',
    offset: 'GMT+08:00',
    locale: 'Asia/Ulaanbaatar',
  },
  AustraliaPerth: {
    value: 'Australia/Perth',
    label: 'GMT+08:00 Australia/Perth',
    offset: 'GMT+08:00',
    locale: 'Australia/Perth',
  },
  AustraliaEucla: {
    value: 'Australia/Eucla',
    label: 'GMT+08:45 Australia/Eucla',
    offset: 'GMT+08:45',
    locale: 'Australia/Eucla',
  },
  AsiaChita: {
    value: 'Asia/Chita',
    label: 'GMT+09:00 Asia/Chita',
    offset: 'GMT+09:00',
    locale: 'Asia/Chita',
  },
  AsiaDili: {
    value: 'Asia/Dili',
    label: 'GMT+09:00 Asia/Dili',
    offset: 'GMT+09:00',
    locale: 'Asia/Dili',
  },
  AsiaJayapura: {
    value: 'Asia/Jayapura',
    label: 'GMT+09:00 Asia/Jayapura',
    offset: 'GMT+09:00',
    locale: 'Asia/Jayapura',
  },
  AsiaKhandyga: {
    value: 'Asia/Khandyga',
    label: 'GMT+09:00 Asia/Khandyga',
    offset: 'GMT+09:00',
    locale: 'Asia/Khandyga',
  },
  AsiaPyongyang: {
    value: 'Asia/Pyongyang',
    label: 'GMT+09:00 Asia/Pyongyang',
    offset: 'GMT+09:00',
    locale: 'Asia/Pyongyang',
  },
  AsiaSeoul: {
    value: 'Asia/Seoul',
    label: 'GMT+09:00 Asia/Seoul',
    offset: 'GMT+09:00',
    locale: 'Asia/Seoul',
  },
  AsiaTokyo: {
    value: 'Asia/Tokyo',
    label: 'GMT+09:00 Asia/Tokyo',
    offset: 'GMT+09:00',
    locale: 'Asia/Tokyo',
  },
  AsiaYakutsk: {
    value: 'Asia/Yakutsk',
    label: 'GMT+09:00 Asia/Yakutsk',
    offset: 'GMT+09:00',
    locale: 'Asia/Yakutsk',
  },
  PacificPalau: {
    value: 'Pacific/Palau',
    label: 'GMT+09:00 Pacific/Palau',
    offset: 'GMT+09:00',
    locale: 'Pacific/Palau',
  },
  AustraliaDarwin: {
    value: 'Australia/Darwin',
    label: 'GMT+09:30 Australia/Darwin',
    offset: 'GMT+09:30',
    locale: 'Australia/Darwin',
  },
  AntarcticaDumontDUrville: {
    value: 'Antarctica/DumontDUrville',
    label: 'GMT+10:00 Antarctica/DumontDUrville',
    offset: 'GMT+10:00',
    locale: 'Antarctica/DumontDUrville',
  },
  AsiaUstNera: {
    value: 'Asia/Ust-Nera',
    label: 'GMT+10:00 Asia/Ust-Nera',
    offset: 'GMT+10:00',
    locale: 'Asia/Ust-Nera',
  },
  AsiaVladivostok: {
    value: 'Asia/Vladivostok',
    label: 'GMT+10:00 Asia/Vladivostok',
    offset: 'GMT+10:00',
    locale: 'Asia/Vladivostok',
  },
  AustraliaBrisbane: {
    value: 'Australia/Brisbane',
    label: 'GMT+10:00 Australia/Brisbane',
    offset: 'GMT+10:00',
    locale: 'Australia/Brisbane',
  },
  AustraliaLindeman: {
    value: 'Australia/Lindeman',
    label: 'GMT+10:00 Australia/Lindeman',
    offset: 'GMT+10:00',
    locale: 'Australia/Lindeman',
  },
  PacificChuuk: {
    value: 'Pacific/Chuuk',
    label: 'GMT+10:00 Pacific/Chuuk',
    offset: 'GMT+10:00',
    locale: 'Pacific/Chuuk',
  },
  PacificGuam: {
    value: 'Pacific/Guam',
    label: 'GMT+10:00 Pacific/Guam',
    offset: 'GMT+10:00',
    locale: 'Pacific/Guam',
  },
  PacificPortMoresby: {
    value: 'Pacific/Port_Moresby',
    label: 'GMT+10:00 Pacific/Port Moresby',
    offset: 'GMT+10:00',
    locale: 'Pacific/Port_Moresby',
  },
  PacificSaipan: {
    value: 'Pacific/Saipan',
    label: 'GMT+10:00 Pacific/Saipan',
    offset: 'GMT+10:00',
    locale: 'Pacific/Saipan',
  },
  AustraliaAdelaide: {
    value: 'Australia/Adelaide',
    label: 'GMT+10:30 Australia/Adelaide',
    offset: 'GMT+10:30',
    locale: 'Australia/Adelaide',
  },
  AustraliaBrokenHill: {
    value: 'Australia/Broken_Hill',
    label: 'GMT+10:30 Australia/Broken Hill',
    offset: 'GMT+10:30',
    locale: 'Australia/Broken_Hill',
  },
  AntarcticaCasey: {
    value: 'Antarctica/Casey',
    label: 'GMT+11:00 Antarctica/Casey',
    offset: 'GMT+11:00',
    locale: 'Antarctica/Casey',
  },
  AntarcticaMacquarie: {
    value: 'Antarctica/Macquarie',
    label: 'GMT+11:00 Antarctica/Macquarie',
    offset: 'GMT+11:00',
    locale: 'Antarctica/Macquarie',
  },
  AsiaMagadan: {
    value: 'Asia/Magadan',
    label: 'GMT+11:00 Asia/Magadan',
    offset: 'GMT+11:00',
    locale: 'Asia/Magadan',
  },
  AsiaSakhalin: {
    value: 'Asia/Sakhalin',
    label: 'GMT+11:00 Asia/Sakhalin',
    offset: 'GMT+11:00',
    locale: 'Asia/Sakhalin',
  },
  AsiaSrednekolymsk: {
    value: 'Asia/Srednekolymsk',
    label: 'GMT+11:00 Asia/Srednekolymsk',
    offset: 'GMT+11:00',
    locale: 'Asia/Srednekolymsk',
  },
  AustraliaCurrie: {
    value: 'Australia/Currie',
    label: 'GMT+11:00 Australia/Currie',
    offset: 'GMT+11:00',
    locale: 'Australia/Currie',
  },
  AustraliaHobart: {
    value: 'Australia/Hobart',
    label: 'GMT+11:00 Australia/Hobart',
    offset: 'GMT+11:00',
    locale: 'Australia/Hobart',
  },
  AustraliaLordHowe: {
    value: 'Australia/Lord_Howe',
    label: 'GMT+11:00 Australia/Lord Howe',
    offset: 'GMT+11:00',
    locale: 'Australia/Lord_Howe',
  },
  AustraliaMelbourne: {
    value: 'Australia/Melbourne',
    label: 'GMT+11:00 Australia/Melbourne',
    offset: 'GMT+11:00',
    locale: 'Australia/Melbourne',
  },
  AustraliaSydney: {
    value: 'Australia/Sydney',
    label: 'GMT+11:00 Australia/Sydney',
    offset: 'GMT+11:00',
    locale: 'Australia/Sydney',
  },
  PacificBougainville: {
    value: 'Pacific/Bougainville',
    label: 'GMT+11:00 Pacific/Bougainville',
    offset: 'GMT+11:00',
    locale: 'Pacific/Bougainville',
  },
  PacificEfate: {
    value: 'Pacific/Efate',
    label: 'GMT+11:00 Pacific/Efate',
    offset: 'GMT+11:00',
    locale: 'Pacific/Efate',
  },
  PacificGuadalcanal: {
    value: 'Pacific/Guadalcanal',
    label: 'GMT+11:00 Pacific/Guadalcanal',
    offset: 'GMT+11:00',
    locale: 'Pacific/Guadalcanal',
  },
  PacificKosrae: {
    value: 'Pacific/Kosrae',
    label: 'GMT+11:00 Pacific/Kosrae',
    offset: 'GMT+11:00',
    locale: 'Pacific/Kosrae',
  },
  PacificNoumea: {
    value: 'Pacific/Noumea',
    label: 'GMT+11:00 Pacific/Noumea',
    offset: 'GMT+11:00',
    locale: 'Pacific/Noumea',
  },
  PacificPohnpei: {
    value: 'Pacific/Pohnpei',
    label: 'GMT+11:00 Pacific/Pohnpei',
    offset: 'GMT+11:00',
    locale: 'Pacific/Pohnpei',
  },
  AsiaAnadyr: {
    value: 'Asia/Anadyr',
    label: 'GMT+12:00 Asia/Anadyr',
    offset: 'GMT+12:00',
    locale: 'Asia/Anadyr',
  },
  AsiaKamchatka: {
    value: 'Asia/Kamchatka',
    label: 'GMT+12:00 Asia/Kamchatka',
    offset: 'GMT+12:00',
    locale: 'Asia/Kamchatka',
  },
  PacificFiji: {
    value: 'Pacific/Fiji',
    label: 'GMT+12:00 Pacific/Fiji',
    offset: 'GMT+12:00',
    locale: 'Pacific/Fiji',
  },
  PacificFunafuti: {
    value: 'Pacific/Funafuti',
    label: 'GMT+12:00 Pacific/Funafuti',
    offset: 'GMT+12:00',
    locale: 'Pacific/Funafuti',
  },
  PacificKwajalein: {
    value: 'Pacific/Kwajalein',
    label: 'GMT+12:00 Pacific/Kwajalein',
    offset: 'GMT+12:00',
    locale: 'Pacific/Kwajalein',
  },
  PacificMajuro: {
    value: 'Pacific/Majuro',
    label: 'GMT+12:00 Pacific/Majuro',
    offset: 'GMT+12:00',
    locale: 'Pacific/Majuro',
  },
  PacificNauru: {
    value: 'Pacific/Nauru',
    label: 'GMT+12:00 Pacific/Nauru',
    offset: 'GMT+12:00',
    locale: 'Pacific/Nauru',
  },
  PacificNorfolk: {
    value: 'Pacific/Norfolk',
    label: 'GMT+12:00 Pacific/Norfolk',
    offset: 'GMT+12:00',
    locale: 'Pacific/Norfolk',
  },
  PacificTarawa: {
    value: 'Pacific/Tarawa',
    label: 'GMT+12:00 Pacific/Tarawa',
    offset: 'GMT+12:00',
    locale: 'Pacific/Tarawa',
  },
  PacificWake: {
    value: 'Pacific/Wake',
    label: 'GMT+12:00 Pacific/Wake',
    offset: 'GMT+12:00',
    locale: 'Pacific/Wake',
  },
  PacificWallis: {
    value: 'Pacific/Wallis',
    label: 'GMT+12:00 Pacific/Wallis',
    offset: 'GMT+12:00',
    locale: 'Pacific/Wallis',
  },
  AntarcticaMcMurdo: {
    value: 'Antarctica/McMurdo',
    label: 'GMT+13:00 Antarctica/McMurdo',
    offset: 'GMT+13:00',
    locale: 'Antarctica/McMurdo',
  },
  EtcGmt_13: {
    value: 'Etc/GMT-13',
    label: 'GMT+13:00 Etc/GMT-13',
    offset: 'GMT+13:00',
    locale: 'Etc/GMT-13',
  },
  PacificAuckland: {
    value: 'Pacific/Auckland',
    label: 'GMT+13:00 Pacific/Auckland',
    offset: 'GMT+13:00',
    locale: 'Pacific/Auckland',
  },
  PacificEnderbury: {
    value: 'Pacific/Enderbury',
    label: 'GMT+13:00 Pacific/Enderbury',
    offset: 'GMT+13:00',
    locale: 'Pacific/Enderbury',
  },
  PacificFakaofo: {
    value: 'Pacific/Fakaofo',
    label: 'GMT+13:00 Pacific/Fakaofo',
    offset: 'GMT+13:00',
    locale: 'Pacific/Fakaofo',
  },
  PacificTongatapu: {
    value: 'Pacific/Tongatapu',
    label: 'GMT+13:00 Pacific/Tongatapu',
    offset: 'GMT+13:00',
    locale: 'Pacific/Tongatapu',
  },
  PacificChatham: {
    value: 'Pacific/Chatham',
    label: 'GMT+13:45 Pacific/Chatham',
    offset: 'GMT+13:45',
    locale: 'Pacific/Chatham',
  },
  EtcGmt_14: {
    value: 'Etc/GMT-14',
    label: 'GMT+14:00 Etc/GMT-14',
    offset: 'GMT+14:00',
    locale: 'Etc/GMT-14',
  },
  PacificApia: {
    value: 'Pacific/Apia',
    label: 'GMT+14:00 Pacific/Apia',
    offset: 'GMT+14:00',
    locale: 'Pacific/Apia',
  },
  PacificKiritimati: {
    value: 'Pacific/Kiritimati',
    label: 'GMT+14:00 Pacific/Kiritimati',
    offset: 'GMT+14:00',
    locale: 'Pacific/Kiritimati',
  },
})
